name: Docker

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
  ALIYUN_HUB_NAME: "${{ secrets.ALIYUN_HUB_NAME }}"
  MM_NOTIFY_URL: "${{ secrets.MM_NOTIFY_URL }}"
  HEARTCHECK_URL: "${{ secrets.HEARTCHECK_URL }}"
  PUSHDEER_URL: "${{ secrets.PUSHDEER_URL }}"
  PUSHDEER_API_KEY: "${{ secrets.PUSHDEER_API_KEY }}"
  
jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Check out code
      uses: actions/checkout@v2

    - name: Replace USERNAME_PLACEHOLDER
      run: bash replace_username.sh


    - name: Login to Docker registry
      run: echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login -u $ALIYUN_REGISTRY_USER --password-stdin $REGISTRY

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Create a new builder instance
      run: docker buildx create --use

    - name: Inspect builder instance
      run: docker buildx inspect --bootstrap

    - name: Build and push image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t $REGISTRY/$ALIYUN_HUB_NAME:latest --push .

    - name: Send notification
      run: |
        data=$(cat trigger.txt)
        curl -X POST $PUSHDEER_URL \
             -d "pushkey=$PUSHDEER_API_KEY" \
             -d "text=镜像同步成功！"

    - name: Send Heartcheck
      run: curl -X GET $HEARTCHECK_URL
